on:
  pull_request:
  push:

jobs:
  zig:
    name: zig CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - run: nix develop --command zig build
      - run: nix develop --command zig build test
      - run: nix develop --command zig fmt . --check
